using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using System.Text.RegularExpressions;

namespace MM.CollectionEnum
{
	public class ScriptCreator
	{
		public enum Type
		{
			Class,
			Static,
			Sealed,
			Struct,
			Enum,
		}

		private const string NEW_LINE = "\n";
		private const string GENERATED_DIRECTORY = "Assets/Scripts/Generated/";
		private const string FILE_TEMPLATE = "/{name}.cs";
		private const string USING_TEMPLATE = "using {using};";

		private const string SCRIPT_TEMPLATE =
			@"{usings}

namespace {namespace}
{
	/// <summary>
	/// Generated by ScriptGenerator class for the {namespace} module
	/// </summary>
	public {type} {name}{extends}
	{
{fields}
	}
}";

		public string Namespace { get; set; }
		public string Name { get; set; }
		public string LocalDirectory { get; set; }
		public Type ScriptType { get; set; }
		public bool Partial { get; set; }

		private List<string> m_Usings = new List<string>();
		private List<string> m_Fields = new List<string>();
		private List<string> m_Extends = new List<string>();

		public void AddUsing(string i_Using)
		{
			m_Usings.Add(i_Using);
		}

		public void AddField(string i_Field)
		{
			m_Fields.Add(i_Field);
		}

		public void AddExtend(string i_Extend)
		{
			m_Extends.Add(i_Extend);
		}

		public void Create()
		{
			string directory = CombinePath(GENERATED_DIRECTORY, LocalDirectory);
			if (!Directory.Exists(directory))
			{
				Directory.CreateDirectory(directory);
			}

			string script = SCRIPT_TEMPLATE
				.Replace("{usings}", string.Join(NEW_LINE, m_Usings.Select(x => USING_TEMPLATE.Replace("{using}", x)).ToArray()))
				.Replace("{namespace}", Namespace)
				.Replace("{type}", GetTypeString(ScriptType))
				.Replace("{name}", Name)
				.Replace("{extends}", m_Extends.Count == 0 ? "" : " : " + string.Join(", ", m_Extends.ToArray()))
				.Replace("{fields}", string.Join(NEW_LINE, m_Fields.ToArray()));

			// Fix line endings
			script = Regex.Replace(script, @"\r\n?|\n", NEW_LINE);

			string scriptPath = CombinePath(directory, FILE_TEMPLATE.Replace("{name}", Name));
			WriteAllTextIfDifferent(scriptPath, script);

			AssetDatabase.Refresh();
		}

		private void WriteAllTextIfDifferent(string i_Path, string i_Content)
		{
			string miniCurrentContent = "";
			if (File.Exists(i_Path))
			{
				string pathContent = File.ReadAllText(i_Path, Encoding.UTF8);
				miniCurrentContent = Regex.Replace(pathContent, @"\s+", "");
			}

			string miniNewContent = Regex.Replace(i_Content, @"\s+", "");

			if (miniCurrentContent != miniNewContent)
			{
				File.WriteAllText(i_Path, i_Content, Encoding.UTF8);
			}
		}

		private string CombinePath(params string[] i_PathSections)
		{
			return string.Join("/", i_PathSections.Select(x => x.Trim('/')).ToArray());
		}

		private string GetTypeString(Type i_Type)
		{
			string partial = Partial ? "partial " : string.Empty;
			switch (i_Type)
			{
				case Type.Static:
					return $"static {partial}class";

				case Type.Sealed:
					return $"sealed {partial}class";

				case Type.Struct:
					return $"{partial}struct";

				case Type.Enum:
					return "enum";

				default:
					return $"{partial}class";
			}
		}
	}
}
